spring:
#  mvc:
#    static-path-pattern: /recources/**
  banner:
    image:
    location: classpath:nobug1.jpg
server:
  port: 8080
config:
  test1: 1
  test2: "testtttt"
  test:
    age: 15
    name: "sdf"
#debug=true
mytest:
  user:
    name: "yoyoyo"
    sex: "women"